version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fastapi_jpq2_user:BHg5jA0nQTNPcTZlpq0D9ojvDoOOvE7S@dpg-csgf0rpu0jms738vuh20-a.oregon-postgres.render.com/fastapi_jpq2
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fastapi_jpq2_user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: BHg5jA0nQTNPcTZlpq0D9ojvDoOOvE7S
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: